### ISSUE TITLE
Filter out junk sentences

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/habitus#45]
Hi @mithunpaul08,
Please implement the filter for junk sentences, as discussed in our meeting, here:
https://github.com/clulab/habitus/blob/main/src/main/scala/org/clulab/habitus/HabitusProcessor.scala#L30

Thanks!

**Comment by kwalcock** [comment]
Junk sentences are filtered, just not at that place right now.  They are filtered with mkDocument and mkDocumentWithRestoreCase.  I guess we're assuming that the newSentences come from a document created with one of those two   One can otherwise call `sentences.filterNot(isBadSentence)` before calling copyDoc.
