### ISSUE TITLE
Duplicate output in the .tsv and .json file

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clulab/habitus#48]
The mentions.tsv and mentions.json file contains duplicated output. For example, for the input document:

> Farmers’ sowing dates ranged from 14 to 31 July for the WS and from 3 to 11 March for the DS.

The `var-read` command produces a `.tsv` file with duplicated rows (the same applies to the `.json`):

```
sowing dates    from 3 to 11 March      XXXX-03-03 -- XXXX-03-11        Farmers ’ sowing dates ranged from 14 to 31 July for the WS and from 3 to 11 March for the DS . 1.txt   N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A
sowing dates    from 3 to 11 March      XXXX-03-03 -- XXXX-03-11        Farmers ’ sowing dates ranged from 14 to 31 July for the WS and from 3 to 11 March for the DS . 1.txt   N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A
sowing dates    from 14 to 31 July      XXXX-07-14 -- XXXX-07-31        Farmers ’ sowing dates ranged from 14 to 31 July for the WS and from 3 to 11 March for the DS . 1.txt   N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A
sowing dates    from 14 to 31 July      XXXX-07-14 -- XXXX-07-31        Farmers ’ sowing dates ranged from 14 to 31 July for the WS and from 3 to 11 March for the DS . 1.txt   N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A     N/A
```

**Comment by kwalcock** [comment]
I would guess that duplicates are getting into the context.  In Eidos there are multiple places where we deduplicate and maybe one is needed here.  I'll write a test case and see what happens.

**Comment by MihaiSurdeanu** [comment]
Thanks!

**Comment by kwalcock** [comment]
Are all rows duplicated or just a few?

**Comment by MihaiSurdeanu** [comment]
all

**Comment by kwalcock** [comment]
It looks like I was distracted enough making sure the output was equivalent that I didn't pay enough attention to what was being output.  It looks like Printer.outputMentions gets some mentions and also contexts as parameters and there are loops for them both.  The left side of those lines comes from the mentions.  The right side comes from context.  Here, the two contexts for each of two mentions are unfortunately all N/A so that nothing can be distinguished.  The printing code implies that the right sides might differ for each mention and therefore not be duplicates.  I don't really know what is supposed to or does go into those contexts.  Something unintended maybe.  There are mentions in the context and perhaps they duplicate the ones passed more directly as parameters.

**Comment by kwalcock** [comment]
In other words, I'll need more information :-(  I see that the README.md file does not have the duplicates.  I'm not sure how that was produced.  Perhaps a recent change resulted in the doubling up of values in the context.

**Comment by MihaiSurdeanu** [comment]
@mithunpaul08 : can you please look at this bug?

**Comment by MihaiSurdeanu** [comment]
I am pretty sure this is a Printer issue, not an Odin one.

**Comment by mithunpaul08** [comment]
Done. fixed. also have added a test case for this.  please merge [pr](https://github.com/clulab/habitus/pull/50)
